# Generated by Django 5.2.7 on 2025-11-19 23:33

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_address_event_end_time_event_is_national_and_more'),
        ('tenants', '0004_alter_user_managers_tenant_request_url_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request_product_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_product', to='events.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request_product', to='events.request')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_product', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
