# Generated by Django 5.2.7 on 2025-11-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_requestproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_time',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
