# Generated by Django 5.2.7 on 2025-11-27 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_end_time_alter_event_start_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdetail',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_detail_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_product_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
