# Generated by Django 5.2.7 on 2025-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_requeststatus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
