# Generated by Django 5.2.7 on 2025-12-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='client_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='distributor_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='distributor_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='retailer_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='retailer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='retailer_store_contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='store_manager_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='store_manager_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='events.client'),
        ),
        migrations.AlterField(
            model_name='request',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='events.distributor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='events.retailer'),
        ),
    ]
