# Generated by Django 5.2.7 on 2025-12-05 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_googlecalendarevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='googlecalendarevent',
            new_name='events_goog_event_i_3d6e25_idx',
            old_name='events_goog_event_i_2a1f8b_idx',
        ),
    ]
