# Generated by Django 5.2.7 on 2025-12-08 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_timezone_request_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=2),
        ),
    ]
