# Generated by Django 5.2.7 on 2025-12-08 17:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=2),
        ),
    ]
