# Generated by Django 5.2.7 on 2025-12-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_events_goog_event_i_2a1f8b_idx_events_goog_event_i_3d6e25_idx'),
        ('events', '0017_alter_event_coordinates'),
    ]

    operations = [
    ]
