# Generated by Django 5.2.7 on 2025-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_merge_20251211_1504"),
    ]

    operations = [
        # --- EVENT MODEL ---
        # Convert event.end_time (time -> timestamp)
        migrations.RunSQL(
            sql="""
                ALTER TABLE events_event
                ALTER COLUMN end_time
                TYPE timestamp with time zone
                USING ('2026-01-01'::date + end_time);
            """,
            reverse_sql="""
                ALTER TABLE events_event
                ALTER COLUMN end_time
                TYPE time without time zone
                USING end_time::time;
            """,
        ),
        # Convert event.start_time (time -> timestamp)
        migrations.RunSQL(
            sql="""
                ALTER TABLE events_event
                ALTER COLUMN start_time
                TYPE timestamp with time zone
                USING ('2026-01-01'::date + start_time);
            """,
            reverse_sql="""
                ALTER TABLE events_event
                ALTER COLUMN start_time
                TYPE time without time zone
                USING start_time::time;
            """,
        ),
        # Now Django can safely alter the fields
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        # --- REQUEST MODEL ---
        # Convert request.end_time (time -> timestamp)
        migrations.RunSQL(
            sql="""
                ALTER TABLE events_request
                ALTER COLUMN end_time
                TYPE timestamp with time zone
                USING ('2026-01-01'::date + end_time);
            """,
            reverse_sql="""
                ALTER TABLE events_request
                ALTER COLUMN end_time
                TYPE time without time zone
                USING end_time::time;
            """,
        ),
        # Convert request.start_time (time -> timestamp)
        migrations.RunSQL(
            sql="""
                ALTER TABLE events_request
                ALTER COLUMN start_time
                TYPE timestamp with time zone
                USING ('2026-01-01'::date + start_time);
            """,
            reverse_sql="""
                ALTER TABLE events_request
                ALTER COLUMN start_time
                TYPE time without time zone
                USING start_time::time;
            """,
        ),
        # And now AlterField for request
        migrations.AlterField(
            model_name="request",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="start_time",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
