# Generated by Django 5.2.7 on 2025-12-13 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststoremanager',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_stores_manager', to='events.request'),
        ),
    ]
