# Generated by Django 5.2.7 on 2025-12-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='events.timezone'),
        ),
    ]
