# Generated by Django 5.2.7 on 2026-01-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_name_notificationgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
