# Generated by Django 5.2.7 on 2026-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_distributor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='store_contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
