# Generated by Django 5.2.7 on 2026-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_retailer_address_alter_retailer_store_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
