# Generated by Django 5.2.7 on 2026-01-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_distributor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
