# Generated by Django 5.2.7 on 2026-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_retailer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestor_email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
