# Generated by Django 5.2.7 on 2026-01-28 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_request_requestor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='events.distributor'),
        ),
        migrations.AddField(
            model_name='event',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.retailer'),
        ),
    ]
