# Generated by Django 5.2.7 on 2026-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_event_distributor_event_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
