# Generated by Django 5.2.7 on 2026-02-19 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_request_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tenant',
        ),
    ]
