# Generated by Django 5.2.7 on 2026-02-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_location_tenant'),
        ('events', '0031_request_approved_by_request_decline_reason'),
    ]

    operations = [
    ]
