# Generated by Django 5.2.7 on 2026-03-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_rmm_asigned_request_rmm_asigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='distributor', to='events.state'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.location'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='events.location'),
        ),
    ]
