# Generated by Django 5.2.7 on 2026-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_distributor_state_retailer_is_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
