# Generated by Django 5.2.7 on 2026-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventtype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
