# Generated by Django 5.2.7 on 2026-03-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_request_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='store_number',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
