# Generated by Django 5.2.7 on 2026-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_request_store_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
