# Generated by Django 5.2.7 on 2026-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_billingentity_request_billing_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='retailer_address',
            field=models.TextField(null=True),
        ),
    ]
