# Generated by Django 5.2.7 on 2026-04-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_billingentity_request_billing_entity'),
        ('recaps', '0020_customfieldvalue_customrecapfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_recap_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to='recaps.customrecaptemplate'),
        ),
    ]
