# Generated by Django 5.2.7 on 2026-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_billingentity_request_billing_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='new_end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
