# Generated by Django 5.2.7 on 2026-04-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_event_custom_recap_template'),
        ('events', '0041_event_new_end_time'),
    ]

    operations = [
    ]
