# Generated by Django 5.2.7 on 2026-04-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_event_address_alter_request_address_and_more'),
        ('events', '0042_merge_20260417_1727'),
    ]

    operations = [
    ]
