# Generated by Django 5.2.7 on 2026-05-20 18:35

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_merge_20260422_2046'),
        ('tenants', '0014_tenant_linked_sheet_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('ba_invited', 'BA invited'), ('ba_accepted', 'BA accepted'), ('ba_declined', 'BA declined'), ('ba_removed', 'BA removed'), ('recap_filed', 'Recap filed'), ('cloned_from', 'Cloned from another request'), ('note_added', 'Note added'), ('nudge_sent', 'Nudge sent')], max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='events.request')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_activity_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'request', '-created_at'], name='ev_actlog_t_r_ctd_idx')],
            },
        ),
    ]
