# Generated by Django 5.2.7 on 2026-05-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_request_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
