# Generated by Django 5.2.7 on 2026-05-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_request_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='scheduling_status',
            field=models.CharField(blank=True, choices=[('already_scheduled', 'Already scheduled with the account'), ('needs_scheduling', 'Needs scheduling by Ignite')], max_length=32, null=True),
        ),
    ]
