# Generated by Django 5.2.7 on 2026-05-31 21:14

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # Build these indexes with CREATE INDEX CONCURRENTLY so the deploy does
    # NOT take an ACCESS EXCLUSIVE lock / block writes on events_event or
    # events_request while the index builds on the production tables.
    # CONCURRENTLY cannot run inside a transaction, so the whole migration
    # must be non-atomic.
    atomic = False

    dependencies = [
        ('events', '0046_request_scheduling_status'),
        ('recaps', '0022_customrecap_external_ba_name'),
        ('tenants', '0016_tenant_default_external_rmm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='event',
            index=models.Index(fields=['tenant', 'date'], name='ev_event_tenant_date_idx'),
        ),
        AddIndexConcurrently(
            model_name='request',
            index=models.Index(fields=['tenant', 'deleted_at', 'date'], name='ev_request_t_del_date_idx'),
        ),
    ]
