# Generated by Django 5.2.7 on 2026-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mileage_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='track_mileage',
            field=models.BooleanField(default=False),
        ),
    ]
