# Generated by Django 5.2.7 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_event_mileage_rate_event_track_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mileage_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
