# Generated by Django 5.2.7 on 2026-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_event_mileage_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exclude_from_dashboard',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
