# Generated by Django 5.2.7 on 2026-07-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_event_exclude_from_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='walkup_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='walkup_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
