# Generated by Django 5.2.7 on 2026-07-20 01:55

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0041_no_show_alerted_at'),
        ('events', '0053_event_walkup_code_event_walkup_code_expires_at'),
        ('tenants', '0031_tenant_master_tracker_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approvals', to='ambassadors.ambassador')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approvals_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approvals', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'period_start', 'period_end'], name='ev_payappr_t_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ambassador', 'period_start', 'period_end'), name='uq_payroll_approval_period')],
            },
        ),
    ]
