# Generated by Django 5.2.7 on 2026-08-03 04:01

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0042_checkin_markets_and_sampling_stops'),
        ('events', '0054_payrollapproval'),
        ('tenants', '0038_seed_checkin_event_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConfirmation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('ba_name', models.CharField(max_length=255)),
                ('ba_email', models.EmailField(max_length=320)),
                ('store_name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('event_type_label', models.CharField(blank=True, default='', max_length=120)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(blank=True, default='', max_length=64)),
                ('products', models.JSONField(blank=True, default=list)),
                ('send_reminders', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='ambassadors.ambassadorevent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_confirmations_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='events.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_confirmations', to='tenants.tenant')),
                ('timezone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_confirmations', to='events.timezone')),
            ],
        ),
        migrations.CreateModel(
            name='EventConfirmationSend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('booked', 'Booked'), ('t24', '24 hours before'), ('t3', '3 hours before')], db_index=True, max_length=16)),
                ('to_email', models.EmailField(blank=True, default='', max_length=320)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='events.eventconfirmation')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventconfirmation',
            index=models.Index(fields=['send_reminders', 'cancelled_at', 'starts_at'], name='ev_confirm_sweep_idx'),
        ),
        migrations.AddIndex(
            model_name='eventconfirmation',
            index=models.Index(fields=['tenant', '-starts_at'], name='ev_confirm_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventconfirmationsend',
            constraint=models.UniqueConstraint(fields=('confirmation', 'stage'), name='uq_event_confirmation_stage'),
        ),
    ]
