# Generated by Django 5.2.7 on 2026-08-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_eventconfirmation_eventconfirmationsend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_non_active_product_required',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
