# Generated by Django 5.2.7 on 2026-08-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0056_request_is_non_active_product_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="account_spend_amount",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="event_assets_needed",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="load_in_time",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="onsite_poc",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="additional_team_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
