# Generated by Django 5.2.7 on 2026-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0057_request_torch_activation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="cases_to_be_shipped",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
