# Generated by Django 5.2.7 on 2025-10-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0002_initial'),
        ('events', '0002_initial'),
        ('jobs', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='companies_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='events.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='companies', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_files_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_files', to='ambassadors.filetype'),
        ),
        migrations.AddField(
            model_name='companyfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='company_files_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies_cover', to='jobs.companyfile'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='companies_profile_image', to='jobs.companyfile'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_review', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_review', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_reviews_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='company_reviews_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_titles_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_titles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_titles_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paytiming',
            name='company_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pay_timings', to='jobs.companyreview'),
        ),
        migrations.AddField(
            model_name='paytiming',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pay_timings_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paytiming',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pay_timings_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rates_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_types_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratetype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rate_types', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ratetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rate_types_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rates', to='jobs.ratetype'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='company_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_scores', to='jobs.companyreview'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_scores_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='review_scores_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
