# Generated by Django 5.2.7 on 2025-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_about_us_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
