# Generated by Django 5.2.7 on 2025-11-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobtitle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='amout',
            new_name='amount',
        ),
    ]
