# Generated by Django 5.2.7 on 2025-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_amout_rate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
