# Generated by Django 5.2.7 on 2025-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_location_job_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='recap_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
