# Generated by Django 5.2.7 on 2025-12-13 14:19

from django.db import migrations, models
from django.utils.text import slugify


def _populate_status_slugs(apps, schema_editor):
    Status = apps.get_model('jobs', 'Status')
    statuses = Status.objects.filter(models.Q(slug__isnull=True) | models.Q(slug=""))
    for status in statuses.iterator():
        status.slug = slugify(status.name)
        status.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_ambassadorjob_recap_uploaded_alter_job_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(
            code=_populate_status_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
