# Generated by Django 5.2.7 on 2025-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_status_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
