# Generated by Django 5.2.7 on 2026-01-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
