# Generated by Django 5.2.7 on 2026-02-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
