# Generated by Django 5.2.7 on 2026-03-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_ambassadorjob_accepted_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='real_amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, null=True),
        ),
    ]
