# Generated by Django 5.2.7 on 2026-03-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_ambassadorjob_real_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
