# Generated by Django 5.2.7 on 2026-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='reminder_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
