# Generated by Django 5.2.7 on 2026-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_ambassadorjob_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='reminder_3h_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
