# Generated by Django 5.2.7 on 2026-04-16 16:14

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_ambassadorjob_reminder_3h_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extension_rate',
            field=models.DecimalField(decimal_places=4, default=jobs.models.get_job_extension_rate_default, max_digits=14, null=True),
        ),
    ]
