# Generated by Django 5.2.7 on 2026-04-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_extension_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='time_blocks_15m',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
