# Generated by Django 5.2.7 on 2026-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_ambassadorjob_time_blocks_15m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorjob',
            name='reminder_15m_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ambassadorjob',
            name='reminder_end_15m_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
