# Generated by Django 5.2.7 on 2026-05-21 01:23

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0020_locationping'),
        ('jobs', '0019_ambassadorjob_reminder_15m_sent_at_and_more'),
        ('tenants', '0014_tenant_linked_sheet_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='favorites_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lifecycle_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('filled', 'Filled'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='max_applications',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='uniform_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='ambassadors.ambassador')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications_decided', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-applied_at',),
                'indexes': [models.Index(fields=['job', 'status'], name='jobs_jobapp_job_id_08192b_idx'), models.Index(fields=['ambassador', 'status'], name='jobs_jobapp_ambassa_c4759d_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'ambassador'), name='uniq_job_ambassador_application')],
            },
        ),
        migrations.CreateModel(
            name='TenantFavoriteAmbassador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_ambassadors_added', to=settings.AUTH_USER_MODEL)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_tenants', to='ambassadors.ambassador')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ambassadors', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'ambassador'), name='uniq_tenant_favorite_ambassador')],
            },
        ),
    ]
