# Generated by Django 5.2.7 on 2026-05-28 21:42

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0021_ambassadorrating'),
        ('jobs', '0021_job_briefing_body_job_briefing_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorJobPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('notify_new_gigs', models.BooleanField(default=True)),
                ('preferred_state_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('min_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to='ambassadors.ambassador')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
