# fly.toml app configuration file generated for spark-api-dev on 2025-10-30T16:34:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spark-api-dev'
primary_region = 'sjc'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'uv run python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
