[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = 
    --reuse-db
    --tb=short
    -v
filterwarnings =
    ignore::DeprecationWarning:gqlauth.*
    ignore::DeprecationWarning:strawberry.*
    ignore::DeprecationWarning:functools.*
testpaths =
    tenants/tests
    tenants/dashboard/tests
    events/tests
    jobs/tests
    ambassadors/tests
    recaps/tests
    receipts/tests
    chats/tests
    academy/tests
    announcements/tests

