# Generated by Django 5.2.7 on 2025-11-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_role_created_by_alter_role_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
