# Generated by Django 5.2.7 on 2025-11-18 23:31

import tenants.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_role_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tenants.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='request_url_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
