# Generated by Django 5.2.7 on 2025-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_user_managers_tenant_request_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='image',
            field=models.ImageField(null=True, upload_to='tenants/images'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='users/images'),
        ),
    ]
