# Generated by Django 5.2.7 on 2025-12-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_googlecalendarconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarconnection',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarconnection',
            name='token_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarconnection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='google_calendar_connections_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
