# Generated by Django 5.2.7 on 2025-12-17 21:39

import django.db.models.deletion
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_convert_googlecalendarconnection_user_to_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=64)),
                ('color_scheme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=16)),
                ('css_variables', models.JSONField(default=utils.utils.default_tenant_theme)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tenant_themes_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tenant_themes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'color_scheme')},
            },
        ),
    ]
