# Generated by Django 5.2.7

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('year', models.IntegerField()),
                ('event_target_goal', models.IntegerField(blank=True, null=True)),
                ('consumer_sampling_goal', models.IntegerField(blank=True, null=True)),
                ('brand_awareness_goal', models.FloatField(blank=True, null=True)),
                ('purchase_intent_goal', models.FloatField(blank=True, null=True)),
                ('female_participation_goal', models.FloatField(blank=True, null=True)),
                ('first_time_buyers_goal', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('tenant', 'user', 'year'), name='tenants_goal_tenant_user_year_uniq'),
                ],
            },
        ),
    ]
