# Generated by Django 5.2.7 on 2026-03-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_goal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
