# Generated by Django 5.2.7 on 2026-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='linked_sheet_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
