# Generated by Django 5.2.7 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_tenant_linked_sheet_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="requires_password_change",
            field=models.BooleanField(default=False),
        ),
    ]
