# Generated by Django 5.2.7 on 2026-05-27 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_user_requires_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_external_rmm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_external_rmm_for_tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
