# Generated by Django 5.2.7 on 2026-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_default_external_rmm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='recap_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Extra email addresses (comma/newline/semicolon-separated) that receive recap-approval emails for this brand, in addition to the RMM, client-role users, and requestor.'),
        ),
    ]
