# Generated by Django 5.2.7 on 2026-06-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_tenant_recap_recipient_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('items', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_snapshots', to='tenants.tenant')),
            ],
        ),
    ]
