# Generated by Django 5.2.7 on 2026-06-01 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_tenantinsightsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantGoal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('target_consumers_reached', models.IntegerField(default=0)),
                ('target_samples_distributed', models.IntegerField(default=0)),
                ('target_products_sold', models.IntegerField(default=0)),
                ('target_total_engagements', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_goals', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'year')},
            },
        ),
    ]
