# Generated by Django 5.2.7 on 2026-06-01 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_tenantgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSentimentSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('sample_size', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_snapshots', to='tenants.tenant')),
            ],
        ),
    ]
