# Generated by Django 5.2.7 on 2026-06-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='scheduled_report_enabled',
            field=models.BooleanField(default=False, help_text='When ON, this brand receives an automated monthly performance-report PDF by email (sent to recap_recipient_emails). OFF by default — opt-in only.'),
        ),
    ]
