# Generated by Django 5.2.7 on 2026-06-09 22:30

from django.db import migrations, models


def _copy_from_scheduled_report_flag(apps, schema_editor):
    """The weekly digest previously piggybacked on scheduled_report_enabled —
    copy it so tenants already receiving the digest keep receiving it."""
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(scheduled_report_enabled=True).update(
        client_weekly_digest_enabled=True
    )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_tenant_scheduled_report_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='client_weekly_digest_enabled',
            field=models.BooleanField(default=False, help_text='When ON, this brand receives the weekly field-marketing digest email (sent to recap_recipient_emails). OFF by default — opt-in only.'),
        ),
        migrations.RunPython(_copy_from_scheduled_report_flag, _noop),
    ]
