# Generated by Django 5.2.7 on 2026-06-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_tenant_client_weekly_digest_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='recap_export_sheet_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
