# Generated by Django 5.2.7 on 2026-06-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_tenant_recap_export_sheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='master_tracker_tab_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
