# Generated by Django 5.2.7 on 2026-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_tenant_master_tracker_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='master_tracker_insert_by_date',
            field=models.BooleanField(default=False),
        ),
    ]
