# Generated by Django 5.2.7 on 2026-06-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_tenant_master_tracker_insert_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='recap_export_on_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='recap_export_tab_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
