# Generated by Django 5.2.7 on 2026-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_tenant_recap_summary_tab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='master_tracker_layout',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
