# Generated by Django 5.2.7 on 2026-07-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_tenant_master_tracker_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
