# Generated by Django 5.2.7 on 2026-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_tenant_checkin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_mileage_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_track_mileage',
            field=models.BooleanField(default=False),
        ),
    ]
