# Generated by Django 5.2.7 on 2026-08-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_tenant_mileage_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_location_mode',
            field=models.CharField(choices=[('address', 'Store address'), ('market', 'Market picker')], default='address', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='checkin_markets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
