# Generated by Django 5.2.7 on 2026-08-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_payrollapproval'),
        ('tenants', '0034_checkin_markets_and_sampling_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_default_for_tenants', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='checkin_training_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
