# Generated by Django 5.2.7 on 2026-08-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_payrollapproval'),
        ('tenants', '0036_tenant_checkin_photo_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_event_types',
            field=models.ManyToManyField(blank=True, related_name='checkin_selectable_for_tenants', to='events.eventtype'),
        ),
    ]
