# Generated by Django 5.2.7 on 2026-08-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0038_seed_checkin_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='suppress_job_reminder_emails',
            field=models.BooleanField(default=False),
        ),
    ]
