# Generated by Django 5.2.7 on 2026-08-03 09:59

from django.db import migrations, models


# Copy of the label/subtitle the check-in page hard-coded for the single
# `checkin_training_url` field. Reproduced verbatim so a tenant configured
# before `checkin_resources` existed — Liquid Death, today the only one — keeps
# a card that reads EXACTLY as it did, rather than silently changing wording the
# moment the page starts rendering the list instead of the one URL.
LEGACY_LABEL = "BA reference & training"
LEGACY_NOTE = "Field guide, video, product sheets"


def seed_resources_from_training_url(apps, schema_editor):
    """Fold each tenant's existing training URL into the new resource list.

    Without this the check-in page would render an empty list for LD the moment
    it prefers `checkin_resources`, and their card would vanish — a regression
    nobody would notice from the Feel Free side of the change.

    Skips tenants that somehow already have a list (re-run safety) and leaves
    `checkin_training_url` in place: the event-confirmation flow still reads it.
    """
    Tenant = apps.get_model("tenants", "Tenant")
    for tenant in (
        Tenant.objects.exclude(checkin_training_url="")
        .exclude(checkin_training_url=None)
        .iterator()
    ):
        if tenant.checkin_resources:
            continue
        url = (tenant.checkin_training_url or "").strip()
        if not url:
            continue
        tenant.checkin_resources = [
            {
                "label": LEGACY_LABEL,
                "kind": "link",
                "url": url,
                "note": LEGACY_NOTE,
            }
        ]
        tenant.save(update_fields=["checkin_resources"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_tenant_suppress_job_reminder_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_resources',
            field=models.JSONField(blank=True, null=True),
        ),
        # Reverse is a no-op: unwinding the AddField above drops the column
        # outright, so there is nothing to put back.
        migrations.RunPython(
            seed_resources_from_training_url,
            migrations.RunPython.noop,
        ),
    ]
