# Generated by Django 5.2.7 on 2026-08-17 23:40

from django.db import migrations, models

# Readable on purpose — this URL gets texted to a 3rd-party agency, not a BA.
# Alphabet matches setup_tenant_checkin (no 0/O/1/I/L). Must never equal
# Torch's BA clock code TH-2HRV3D.
TORCH_RECAP_CODE = "TH-AGENCY"


def mint_torch_recap_code(apps, schema_editor):
    """Turn on Torch's recap-only URL without touching the BA clock link."""
    Tenant = apps.get_model("tenants", "Tenant")
    tenant = (
        Tenant.objects.filter(checkin_code="TH-2HRV3D").first()
        or Tenant.objects.filter(slug="torch-thc").first()
        or Tenant.objects.filter(request_url_name="keee-torch-thc").first()
    )
    if tenant is None:
        return
    if (getattr(tenant, "checkin_recap_code", None) or "").strip():
        return
    if Tenant.objects.filter(checkin_code__iexact=TORCH_RECAP_CODE).exists():
        return
    if Tenant.objects.filter(checkin_recap_code__iexact=TORCH_RECAP_CODE).exists():
        return
    tenant.checkin_recap_code = TORCH_RECAP_CODE
    tenant.save(update_fields=["checkin_recap_code"])


def unmint_torch_recap_code(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Tenant.objects.filter(checkin_recap_code=TORCH_RECAP_CODE).update(
        checkin_recap_code=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0040_tenant_checkin_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="checkin_recap_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, null=True, unique=True
            ),
        ),
        migrations.RunPython(mint_torch_recap_code, unmint_torch_recap_code),
    ]
