# Generated by Django 5.2.7 on 2026-10-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0044_enable_torch_weekly_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_recap_excludes_aggregates',
            field=models.BooleanField(default=False),
        ),
    ]
