# Generated by Django 5.2.7 on 2026-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0050_tenant_activation_mix_includes_walkups'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='checkin_team_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='checkin_team_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='checkin_team_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
