# Generated by Django 5.2.7 on 2026-05-30 17:25

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0046_request_scheduling_status'),
        ('tenants', '0016_tenant_default_external_rmm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('image', models.CharField(max_length=1024)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consumer_email', models.CharField(blank=True, max_length=254, null=True)),
                ('consumer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('review_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_receipts', to='events.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_consumer_receipts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_receipts', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-submitted_at',),
                'indexes': [models.Index(fields=['tenant', 'status', '-submitted_at'], name='rcpt_tenant_status_sub_idx')],
            },
        ),
    ]
