# Generated by Django 5.2.7 on 2026-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_consumerreceipt_paid_at_consumerreceipt_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerreceipt',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='image_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='ocr_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='ocr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='ocr_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='ocr_store',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consumerreceipt',
            name='ocr_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='receiptcampaign',
            name='budget_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='receiptcampaign',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
