# Generated by Django 5.2.7 on 2026-07-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_consumerreceipt_flag_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerreceipt',
            name='payout_method',
            field=models.CharField(blank=True, default='paypal', max_length=16),
        ),
    ]
