# Generated by Django 5.2.7 on 2026-07-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_consumerreceipt_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptcampaign',
            name='hero_image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='receiptcampaign',
            name='product_image',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
