# Generated by Django 5.2.7 on 2026-05-29 03:42

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0022_shiftextensionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('doc_type', models.CharField(choices=[('government_id', 'Government ID'), ('food_handler', 'Food Handler Card'), ('alcohol_cert', 'Alcohol Server Certification (TABC/etc.)'), ('drivers_license', "Driver's License"), ('certification', 'Other Certification'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(max_length=1024, null=True, upload_to='documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ambassador', 'status'], name='documents_a_ambassa_81ac29_idx'), models.Index(fields=['expires_on'], name='documents_a_expires_d3ea23_idx')],
            },
        ),
    ]
