# Generated by Django 5.2.7 on 2025-10-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0001_initial'),
        ('events', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors', to='events.location'),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_events', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_events_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_events', to='events.event'),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_events', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_events_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorfile',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_files', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='ambassadorfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_files_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_files_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadornote',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_notes', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='ambassadornote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_notes_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadornote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_notes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ambassadornote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_notes_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_reviews', to='events.client'),
        ),
        migrations.AddField(
            model_name='ambassadorreview',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorskill',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_skills', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='ambassadorskill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_skills_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorskill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_skills', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ambassadorskill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_skills_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadortrait',
            name='ambassador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_traits', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='ambassadortrait',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_traits_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadortrait',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_traits_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadortrait',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_traits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files_types_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files_types_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorfile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_files', to='ambassadors.filetype'),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='skill_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='skills', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='skill_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ambassadorskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassadors_skills', to='ambassadors.skill'),
        ),
    ]
