# Generated by Django 5.2.7 on 2025-12-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0005_add_ambassador_creation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ambassador',
            new_name='ambassadors_is_acti_b7cef8_idx',
            old_name='ambassadors_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='ambassador',
            new_name='ambassadors_user_id_586f5e_idx',
            old_name='ambassadors_user_is_a_idx',
        ),
        migrations.RenameIndex(
            model_name='ambassadorinvitation',
            new_name='ambassadors_email_7fdfed_idx',
            old_name='ambassadors_email_is_u_idx',
        ),
        migrations.RenameIndex(
            model_name='ambassadorinvitation',
            new_name='ambassadors_email_5d0912_idx',
            old_name='ambassadors_email_is_e_idx',
        ),
        migrations.RenameIndex(
            model_name='ambassadorinvitation',
            new_name='ambassadors_token_bedffd_idx',
            old_name='ambassadors_token_idx',
        ),
        migrations.RenameIndex(
            model_name='ambassadorinvitation',
            new_name='ambassadors_expires_43afc2_idx',
            old_name='ambassadors_expires_idx',
        ),
        migrations.AlterField(
            model_name='ambassadorinvitation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_invitations_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambassadorinvitation',
            name='used_at',
            field=models.DateTimeField(null=True),
        ),
    ]
