# Generated by Django 5.2.7 on 2025-12-11 23:03

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0007_convert_user_to_onetoone'),
        ('events', '0019_event_date_alter_event_end_time_and_more'),
        ('jobs', '0008_ambassadorjob_recap_uploaded_alter_job_end_date_and_more'),
        ('tenants', '0007_alter_googlecalendarconnection_refresh_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_status_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_status', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_status_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_types_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_types_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='source_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('clock_time', models.DateTimeField()),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='events.event')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='jobs.job')),
                ('timezone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='events.timezone')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance_updated_by', to=settings.AUTH_USER_MODEL)),
                ('attendance_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='ambassadors.attendancestatus')),
                ('attendace_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='ambassadors.attendancetype')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='attendance', to='ambassadors.source')),
            ],
        ),
    ]
