# Generated by Django 5.2.7 on 2025-12-13 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0008_attendancestatus_attendancetype_source_attendance'),
        ('events', '0019_event_date_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambassadorreview',
            options={'verbose_name': 'Ambassador Review', 'verbose_name_plural': 'Ambassador Reviews'},
        ),
        migrations.AlterUniqueTogether(
            name='ambassadorreview',
            unique_together={('ambassador', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='ambassadorskill',
            unique_together={('ambassador', 'skill')},
        ),
    ]
