# Generated by Django 5.2.7 on 2025-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0009_alter_ambassadorreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestatus',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='attendancetype',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
