# Generated by Django 5.2.7 on 2026-01-13 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0011_grouptype_ambassadorgroup_usergroup'),
        ('jobs', '0011_remove_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorinvitation',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='jobs.job'),
        ),
    ]
