# Generated by Django 5.2.7 on 2026-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0012_ambassadorinvitation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
