# Generated by Django 5.2.7 on 2026-02-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0013_ambassador_phone'),
        ('events', '0030_request_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador', to='events.location'),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='t_shirt_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ambassador',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
