# Generated by Django 5.2.7 on 2026-02-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0014_ambassador_location_ambassador_t_shirt_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='tenant',
        ),
    ]
