# Generated by Django 5.2.7 on 2026-02-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0015_remove_skill_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassadorskill',
            name='tenant',
        ),
    ]
