# Generated by Django 5.2.7 on 2026-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0016_remove_ambassadorskill_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
