# Generated by Django 5.2.7 on 2026-05-02 21:07

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0017_ambassador_about_me'),
        ('jobs', '0018_ambassadorjob_time_blocks_15m'),
        ('tenants', '0013_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorGroupJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_group_jobs_created_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_links', to='ambassadors.ambassadorgroup')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_group_links', to='jobs.job')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_group_links', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_group_jobs_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'job'), name='unique_ambassador_group_job')],
            },
        ),
    ]
