# Generated by Django 5.2.7 on 2026-05-19 07:39

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0019_pushdevice'),
        ('events', '0043_merge_20260422_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('foreground', 'Foreground'), ('background', 'Background'), ('clock_in', 'Clock-in'), ('clock_out', 'Clock-out')], default='background', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='ambassadors.ambassador')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['ambassador', '-recorded_at'], name='ambassadors_ambassa_81c609_idx'), models.Index(fields=['event', '-recorded_at'], name='ambassadors_event_i_83d507_idx')],
            },
        ),
    ]
