# Generated by Django 5.2.7 on 2026-05-26 21:54

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0020_locationping'),
        ('events', '0045_request_deleted_at'),
        ('tenants', '0015_user_requires_password_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('score', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('by_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_ratings_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambassador_ratings', to='events.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_ratings', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_ratings_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ambassador', '-created_at'], name='ambassadors_ambassa_67007c_idx'), models.Index(fields=['event'], name='ambassadors_event_i_208d28_idx'), models.Index(fields=['tenant', 'by_client'], name='ambassadors_tenant__1d54cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('ambassador', 'event', 'created_by'), name='uniq_ambassador_rating_per_gig_per_rater')],
            },
        ),
    ]
