# Generated by Django 5.2.7 on 2026-05-29 00:34

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0021_ambassadorrating'),
        ('events', '0046_request_scheduling_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftExtensionRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('minutes_requested', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('approved_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_requests_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='ambassadors_event_i_bcb60d_idx'), models.Index(fields=['status', '-created_at'], name='ambassadors_status_a790cf_idx')],
            },
        ),
    ]
