# Generated by Django 5.2.7 on 2026-05-29 09:13

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0022_shiftextensionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='college',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='headshot',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='in_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ambassador',
            name='resume',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.CreateModel(
            name='AmbassadorPhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('image', models.CharField(max_length=1024)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambassador_photos_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ambassador', '-created_at'], name='ambassadors_ambassa_f0d66b_idx')],
            },
        ),
    ]
