# Generated by Django 5.2.7 on 2026-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0023_ambassador_bio_ambassador_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorevent',
            name='activation_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='recap_nudge_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
