# Generated by Django 5.2.7 on 2026-06-06 04:36

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0025_pushnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('shift_offers', models.BooleanField(default=True)),
                ('reminders', models.BooleanField(default=True)),
                ('chat', models.BooleanField(default=True)),
                ('pay', models.BooleanField(default=True)),
                ('gigs', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
