# Generated by Django 5.2.7 on 2026-06-06 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0027_openshift'),
        ('events', '0048_dedupe_timezones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openshift',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='openshift',
            index=models.Index(fields=['notified_at'], name='ambassadors_notifie_98f339_idx'),
        ),
    ]
