# Generated by Django 5.2.7 on 2026-06-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0030_skill_ambassadors_skill_name_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorevent',
            name='confirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambassadorevent',
            name='unconfirmed_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
