# Generated by Django 5.2.7 on 2026-06-18 08:05

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0032_backfill_approved_job_bookings'),
        ('events', '0050_event_mileage_rate_event_track_mileage'),
        ('tenants', '0025_tenant_client_weekly_digest_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rate_per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reimbursement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_sessions', to='ambassadors.ambassador')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_sessions', to='events.event')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage_sessions', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MileageBreadcrumb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breadcrumbs', to='ambassadors.mileagesession')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mileagesession',
            index=models.Index(fields=['ambassador', 'event', 'status'], name='ambassadors_ambassa_75409e_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagesession',
            index=models.Index(fields=['event', '-started_at'], name='ambassadors_event_i_7751ec_idx'),
        ),
        migrations.AddIndex(
            model_name='mileagebreadcrumb',
            index=models.Index(fields=['session', 'recorded_at'], name='ambassadors_session_98890d_idx'),
        ),
    ]
