# Generated by Django 5.2.7 on 2026-06-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0033_mileagesession_mileagebreadcrumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagesession',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mileagesession',
            name='route_source',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
