# Generated by Django 5.2.7 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0034_mileagesession_route_mileagesession_route_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileagesession',
            name='rate_per_mile',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
