# Generated by Django 5.2.7 on 2026-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0036_shiftextensionrequest_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftextensionrequest',
            name='decision_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
