# Generated by Django 5.2.7 on 2026-07-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0038_ambassadorevent_activation_nudge_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorevent',
            name='pre_shift_checklist_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
