# Generated by Django 5.2.7 on 2026-07-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0039_ambassadorevent_pre_shift_checklist_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorevent',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin'), ('apply', 'Applied'), ('claim', 'Claimed open shift'), ('assign', 'Assigned'), ('walkup', 'Walk-up')], db_index=True, default='admin', max_length=16),
        ),
    ]
