# Generated by Django 5.2.7 on 2026-07-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0040_ambassadorevent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadorevent',
            name='no_show_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
