# Generated by Django 5.2.7 on 2026-08-02 19:34

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0041_no_show_alerted_at'),
        ('events', '0054_payrollapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplingStop',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=512)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_stops', to='ambassadors.ambassador')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_stops', to='events.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'recorded_at'], name='ambassadors_event_i_faf23d_idx'), models.Index(fields=['ambassador', '-recorded_at'], name='ambassadors_ambassa_59189c_idx')],
            },
        ),
    ]
