"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
from pathlib import Path
from datetime import timedelta
from decimal import Decimal, InvalidOperation
from django.core.exceptions import ImproperlyConfigured
from gqlauth.settings_type import GqlAuthSettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))

environ.Env.read_env(BASE_DIR / ".env")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:3000"]
)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "strawberry_django",
    "corsheaders",
    "storages",
    "django_rq",
    "django_extensions",
    "gqlauth",
    "tenants",
    "events",
    "ambassadors",
    "jobs",
    "recaps",
    "chats",
    "digest",
]

AUTH_USER_MODEL = "tenants.User"

STRAWBERRY_DJANGO = {
    "MAP_AUTO_ID_AS_GLOBAL_ID": True,
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "gqlauth.core.middlewares.django_jwt_middleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "tenants.auth_backends.CustomAuthenticationBackend",
]

GQL_AUTH = GqlAuthSettings(
    # JWT_SECRET_KEY=env('SECRET_KEY'),
    # JWT_ALGORITHM="H256",
    # ALLOW_DELETE_ACCOUNT=True,
    JWT_LONG_RUNNING_REFRESH_TOKEN=True,
    JWT_REFRESH_EXPIRATION_DELTA=timedelta(days=10),
    JWT_EXPIRATION_DELTA=timedelta(days=1),
    LOGIN_REQUIRE_CAPTCHA=False,
    REGISTER_REQUIRE_CAPTCHA=False,
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}
DATABASES["default"]["CONN_MAX_AGE"] = 60


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Storage Configuration for Google Cloud Storage
GS_BUCKET_NAME = env("GS_BUCKET_NAME", default="")
GS_PROJECT_ID = env("GS_PROJECT_ID", default=None)

# GCS Credentials - can be JSON string or file path
GS_CREDENTIALS_JSON = env("GS_CREDENTIALS", default=None)
if GS_CREDENTIALS_JSON:
    import json

    try:
        # Parse the JSON credentials
        GS_CREDENTIALS = json.loads(GS_CREDENTIALS_JSON)
    except json.JSONDecodeError as e:
        # Log the error but don't crash - allows development without GCS
        print(f"Warning: Invalid GCS_CREDENTIALS JSON: {e}")
        print("GCS functionality will be disabled. Please check your .env file.")
        GS_CREDENTIALS = None
else:
    GS_CREDENTIALS = None

# Bucket-level access is set to public (object-viewer for allUsers) on
# sparkio-production / sparkio-new. The Cloud Run service account ships
# with a token only — no private key — so generate_signed_url() raises
# "you need a private key to sign credentials" and every FileField.url
# bubbles a GraphQL error (product images, tenant logos, recap files).
# Switching to public URL mode bypasses signing entirely: django-storages
# returns https://storage.googleapis.com/<bucket>/<key> which the public
# bucket serves directly.
GS_DEFAULT_ACL = None  # Use bucket's default ACL (uniform bucket-level access)
GS_QUERYSTRING_AUTH = env.bool("GS_QUERYSTRING_AUTH", default=False)

# File storage backend
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"

# Media files configuration
MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
MEDIA_ROOT = "media/"

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = env("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = env("GOOGLE_OAUTH_CLIENT_SECRET", default="")
GOOGLE_OAUTH_REDIRECT_URI = env(
    "GOOGLE_OAUTH_REDIRECT_URI",
    default="http://localhost:8000/api/v1/google-calendar/callback",
)

# Google Calendar Service Account Credentials
GOOGLE_CALENDAR_ID = env("GOOGLE_CALENDAR_ID", default="primary")
GOOGLE_CALENDAR_CREDENTIALS_JSON = env("GOOGLE_CALENDAR_CREDENTIALS", default=None)
if GOOGLE_CALENDAR_CREDENTIALS_JSON:
    import json

    try:
        GOOGLE_CALENDAR_CREDENTIALS = json.loads(GOOGLE_CALENDAR_CREDENTIALS_JSON)
    except json.JSONDecodeError as e:
        print(f"Warning: Invalid GOOGLE_CALENDAR_CREDENTIALS JSON: {e}")
        GOOGLE_CALENDAR_CREDENTIALS = None
else:
    GOOGLE_CALENDAR_CREDENTIALS = None

# Django-RQ Configuration
RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "URL": env("CELERY_BROKER_URL", default="redis://localhost:6379/0"),
    },
    "high": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "URL": env("CELERY_BROKER_URL", default="redis://localhost:6379/0"),
    },
    "low": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
        "URL": env("CELERY_BROKER_URL", default="redis://localhost:6379/0"),
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 1025

# RQ settings for commit mode (enqueue jobs when DB transaction commits)
RQ = {
    "COMMIT_MODE": "on_db_commit",  # Ensures jobs wait for DB commits
}

MAIL_DRIVER = env("MAIL_DRIVER", default="mailpit")  # mailpit, resend
RESEND_API_KEY = env("RESEND_API_KEY", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="Spark <onboarding@resend.dev>")
REQUEST_REVIEW_COPY_EMAILS = env.list("REQUEST_REVIEW_COPY_EMAILS", default=[])
RECAP_REVIEW_COPY_EMAILS = env.list("RECAP_REVIEW_COPY_EMAILS", default=[])
# Comma-separated admin emails alerted when a new BA signs up via
# any public path (createPublicAmbassador / Apple / Google).
# Empty default → no alert. Set this in prod env to plug the silent-
# signup failure mode.
NEW_AMBASSADOR_ALERT_EMAILS = env.list("NEW_AMBASSADOR_ALERT_EMAILS", default=[])
REQUEST_REVIEW_COPY_DELAY_SECONDS = env.float(
    "REQUEST_REVIEW_COPY_DELAY_SECONDS",
    default=2.0,
)


CLIENT_FRONTEND_URL = env("CLIENT_FRONTEND_URL", default="http://localhost:3000")
AMBASSADOR_FRONTEND_URL = env(
    "AMBASSADOR_FRONTEND_URL", default="http://localhost:3000"
)
ADMIN_FRONTEND_URL = env("ADMIN_FRONTEND_URL", default="http://localhost:3000")
EMAIL_LOGO_CID = env("EMAIL_LOGO_CID", default="spark-logo")
EMAIL_LOGO_PATH = env(
    "EMAIL_LOGO_PATH",
    default=str(BASE_DIR / "tenants/static/tenants/spark_logo.png"),
)
EMAIL_LOGO_URL = env(
    "EMAIL_LOGO_URL",
    default="",
)
ONESIGNAL_APP_ID = env("ONESIGNAL_APP_ID", default="")
ONESIGNAL_REST_API_KEY = env("ONESIGNAL_REST_API_KEY", default="")
ONESIGNAL_API_URL = env("ONESIGNAL_API_URL", default="https://api.onesignal.com")
ONESIGNAL_TARGET_CHANNEL = env("ONESIGNAL_TARGET_CHANNEL", default="push")
ONESIGNAL_TIMEOUT_SECONDS = env.float("ONESIGNAL_TIMEOUT_SECONDS", default=10.0)

# Expo Push relay (used by spark-mobile via expo-notifications).
# EXPO_PUSH_ACCESS_TOKEN is optional — recommended in production so
# Expo can throttle/identify the sender. Without it, requests still
# succeed but are subject to anonymous rate limits.
EXPO_PUSH_API_URL = env("EXPO_PUSH_API_URL", default="https://exp.host/--/api/v2/push")
EXPO_PUSH_ACCESS_TOKEN = env("EXPO_PUSH_ACCESS_TOKEN", default="")
EXPO_PUSH_TIMEOUT_SECONDS = env.float("EXPO_PUSH_TIMEOUT_SECONDS", default=10.0)

# Sign in with Apple — `aud` claims we accept on identity tokens.
# Comma-separated list of bundle ids / services ids. Defaults to the
# spark-mobile bundle id.
APPLE_OAUTH_AUDIENCES = env.list(
    "APPLE_OAUTH_AUDIENCES",
    default=["co.igniteproductions.spark"],
)
APPLE_OAUTH_KEYS_URL = env(
    "APPLE_OAUTH_KEYS_URL", default="https://appleid.apple.com/auth/keys"
)
APPLE_OAUTH_ISSUER = env(
    "APPLE_OAUTH_ISSUER", default="https://appleid.apple.com"
)

# Sign in with Google — `aud` claims we accept on id tokens. The web
# client id is used by the legacy admin app; the iOS client id is what
# spark-mobile sends. Both should be listed.
GOOGLE_OAUTH_AUDIENCES = env.list(
    "GOOGLE_OAUTH_AUDIENCES",
    default=[
        # Web client (existing).
        "490085168610-ork3r7pnev7e9ksmkf1osp7v6c34g851.apps.googleusercontent.com",
    ],
)

# Gemini AI Configuration
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")

_job_extension_rate_default = env("JOB_EXTENSION_RATE_DEFAULT", default=8)
if _job_extension_rate_default in (None, ""):
    JOB_EXTENSION_RATE_DEFAULT = None
else:
    try:
        JOB_EXTENSION_RATE_DEFAULT = Decimal(_job_extension_rate_default)
    except InvalidOperation as exc:
        raise ImproperlyConfigured(
            "JOB_EXTENSION_RATE_DEFAULT must be a valid decimal value."
        ) from exc

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "events": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "tenants": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "rq.worker": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
