# Generated by Django 5.2.7 on 2025-10-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('jobs', '0003_alter_company_about_us_alter_company_address_and_more'),
        ('tenants', '0002_alter_role_created_by_alter_role_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobchatroom',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_chat_rooms', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobchatroom',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_chat_rooms', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='jobchatroom',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_chat_rooms_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobchatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='job_chat_rooms_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroomcompaniemessage',
            name='job_chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chatroom_companies_messages', to='chats.jobchatroom'),
        ),
        migrations.AddField(
            model_name='chatroomambassadormessage',
            name='job_chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chatroom_ambassador_messages', to='chats.jobchatroom'),
        ),
    ]
