# Generated by Django 5.2.7 on 2026-05-29 07:39

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_unified_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ChatMessageAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('file', models.FileField(max_length=1024, upload_to='chat_attachments/')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('file', 'Other file')], default='file', max_length=16)),
                ('original_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('byte_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chats.chatmessage')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['message'], name='chats_attach_message_idx')],
            },
        ),
    ]
