# Generated by Django 5.2.7 on 2026-10-10 18:15

import django.db.models.deletion
import jobboard.models
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0043_payablemileageclaim'),
        ('events', '0063_field_marketing_delete_and_times'),
        ('jobs', '0027_job_deleted_at'),
        ('tenants', '0050_tenant_activation_mix_includes_walkups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=jobboard.models.new_board_token, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_board', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='JobBoardGig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_shifts', models.PositiveSmallIntegerField()),
                ('listed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_board_gig', to='events.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_board_gigs', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobBoardBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_board_bookings', to='ambassadors.ambassador')),
                ('ambassador_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ambassadors.ambassadorevent')),
                ('ambassador_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.ambassadorjob')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventconfirmation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_board_bookings', to='events.event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_board_bookings', to='tenants.tenant')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['phone'], name='jobboard_booking_phone_idx'), models.Index(fields=['email'], name='jobboard_booking_email_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('event', 'phone'), name='jobboard_one_live_booking_per_phone'), models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('event', 'email'), name='jobboard_one_live_booking_per_email')],
            },
        ),
    ]
