# Generated by Django 5.2.7 on 2025-10-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambassadors', '0002_initial'),
        ('events', '0002_initial'),
        ('recaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recaps_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recap',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='events.event'),
        ),
        migrations.AddField(
            model_name='recap',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recapfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_files_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recapfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_files', to='ambassadors.filetype'),
        ),
        migrations.AddField(
            model_name='recapfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_files_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recap',
            name='recap_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='recaps.recapfile'),
        ),
    ]
