# Generated by Django 5.2.7 on 2025-12-03 16:06

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0003_alter_recap_updated_by_alter_recapfile_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recapfile',
            name='url',
        ),
        migrations.AddField(
            model_name='recapfile',
            name='file',
            field=models.FileField(null=True, upload_to='recap_files/'),
        ),
        migrations.CreateModel(
            name='RecapRecapFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_recap_file_created_by', to=settings.AUTH_USER_MODEL)),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_recap_file', to='recaps.recap')),
                ('recap_file', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_recap_file', to='recaps.recapfile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_recap_file_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
