# Generated by Django 5.2.7 on 2025-12-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_ambassadorjob_recap_uploaded_alter_job_end_date_and_more'),
        ('recaps', '0004_remove_recapfile_url_recapfile_file_recaprecapfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='jobs.job'),
        ),
    ]
