# Generated by Django 5.2.7 on 2025-12-16 04:36

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0009_alter_ambassadorreview_options_and_more'),
        ('events', '0021_alter_location_code'),
        ('recaps', '0005_recap_job'),
        ('tenants', '0008_convert_googlecalendarconnection_user_to_onetoone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='ambassador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='ambassadors.ambassador'),
        ),
        migrations.AddField(
            model_name='recap',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recap',
            name='products_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='events.retailer'),
        ),
        migrations.AddField(
            model_name='recap',
            name='submited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='events.timezone'),
        ),
        migrations.AddField(
            model_name='recap',
            name='total_earnings',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='total_engagements',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='AccountFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('do_differently_feedback', models.TextField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('corpo_card', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='account_feedback_created_by', to=settings.AUTH_USER_MODEL)),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='account_feedback', to='recaps.recap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='account_feedback_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerEngagements',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('total_consumer', models.IntegerField()),
                ('first_time_consumers', models.IntegerField()),
                ('brand_aware_consumers', models.IntegerField()),
                ('willing_to_purchase_consumers', models.IntegerField()),
                ('not_willing_consumers', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_engagements_created_by', to=settings.AUTH_USER_MODEL)),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_engagements', to='recaps.recap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_engagements_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('demographics', models.CharField(max_length=100, null=True)),
                ('feedback', models.TextField(null=True)),
                ('quotes', models.TextField(null=True)),
                ('positive_stories', models.TextField(null=True)),
                ('reasons_to_decline', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_feedback_created_by', to=settings.AUTH_USER_MODEL)),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_feedback', to='recaps.recap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='consumer_feedback_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecapCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file_recap_categories_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='file_recap_categories', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='file_recap_categories_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recapfile',
            name='file_recap_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_files', to='recaps.filerecapcategory'),
        ),
        migrations.CreateModel(
            name='ProductSamples',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_samples_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_samples', to='events.product')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_samples', to='recaps.recap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_samples_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfGood',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type_of_goods_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='type_of_goods', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type_of_goods_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sales_performance_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_performance', to='events.product')),
                ('recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_performance', to='recaps.recap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sales_performance_updated_by', to=settings.AUTH_USER_MODEL)),
                ('type_of_good', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_performance', to='recaps.typeofgood')),
            ],
        ),
    ]
