# Generated by Django 5.2.7 on 2025-12-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0006_recap_ambassador_recap_approved_recap_products_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recap',
            name='recap_file',
        ),
        migrations.AddField(
            model_name='recapfile',
            name='recap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_files', to='recaps.recap'),
        ),
        migrations.DeleteModel(
            name='RecapRecapFile',
        ),
    ]
