# Generated by Django 5.2.7 on 2026-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0007_remove_recap_recap_file_recapfile_recap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='account_spend_amount',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
