# Generated by Django 5.2.7 on 2026-01-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0008_recap_account_spend_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapfile',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
