# Generated by Django 5.2.7 on 2026-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0009_alter_recapfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerfeedback',
            name='demographics',
            field=models.TextField(null=True),
        ),
    ]
