# Generated by Django 5.2.7 on 2026-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0010_alter_consumerfeedback_demographics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recap',
            name='name',
            field=models.TextField(),
        ),
    ]
