# Generated by Django 5.2.7 on 2026-02-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0011_alter_recap_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recapfile',
            name='file',
            field=models.FileField(max_length=1024, null=True, upload_to='recap_files/'),
        ),
    ]
