# Generated by Django 5.2.7 on 2026-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0012_alter_recapfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='total_cans_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='total_packs_sold',
            field=models.IntegerField(null=True),
        ),
    ]
