# Generated by Django 5.2.7 on 2026-03-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0013_recap_total_cans_sold_recap_total_packs_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='filling_for_ambassador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recap',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recap',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
