# Generated by Django 5.2.7 on 2026-03-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0014_recap_filling_for_ambassador_recap_incomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfeedback',
            name='was_corpo_card_used',
            field=models.BooleanField(default=False),
        ),
    ]
