# Generated by Django 5.2.7 on 2026-03-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0015_accountfeedback_was_corpo_card_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='competitive_presence',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recap',
            name='traffic_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
