# Generated by Django 5.2.7 on 2026-03-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_location_event_state_request_location_and_more'),
        ('recaps', '0016_recap_competitive_presence_recap_traffic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='events.location'),
        ),
        migrations.AddField(
            model_name='recap',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recaps', to='events.state'),
        ),
    ]
