# Generated by Django 5.2.7 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0017_recap_location_recap_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerengagements',
            name='brand_aware_consumers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumerengagements',
            name='first_time_consumers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumerengagements',
            name='not_willing_consumers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumerengagements',
            name='total_consumer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumerengagements',
            name='willing_to_purchase_consumers',
            field=models.IntegerField(null=True),
        ),
    ]
