# Generated by Django 5.2.7 on 2026-04-09 19:16

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0017_ambassador_about_me'),
        ('events', '0040_billingentity_request_billing_entity'),
        ('jobs', '0016_ambassadorjob_reminder_3h_sent_at'),
        ('recaps', '0018_alter_consumerengagements_brand_aware_consumers_and_more'),
        ('tenants', '0013_tenant_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRecap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField()),
                ('submitted_at', models.DateTimeField(null=True)),
                ('total_engagements', models.IntegerField(null=True)),
                ('filling_for_ambassador', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('incomplete', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('used_corpo_card', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambassador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='ambassadors.ambassador')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_created_by', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='events.event')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='jobs.job')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='events.location')),
                ('retailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='events.retailer')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='events.state')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='tenants.tenant')),
                ('timezone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='events.timezone')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecapFieldType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_field_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_field_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecapProductSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_product_sample_created_by', to=settings.AUTH_USER_MODEL)),
                ('custom_recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_product_sample', to='recaps.customrecap')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_product_sample', to='events.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_product_sample_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecapSalePerformance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_sale_performance_created_by', to=settings.AUTH_USER_MODEL)),
                ('custom_recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_sale_performance', to='recaps.customrecap')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_sale_performance', to='events.product')),
                ('type_of_good', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_sale_performance', to='recaps.typeofgood')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_sales_performance_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecapTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField()),
                ('product_samples', models.BooleanField(default=False)),
                ('sales_performance', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_template_created_by', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_template', to='events.eventtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_template', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_template_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customrecap',
            name='custom_recap_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap', to='recaps.customrecaptemplate'),
        ),
        migrations.CreateModel(
            name='RecapSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_section_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recap_section', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recap_section_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_updated_by', to=settings.AUTH_USER_MODEL)),
                ('custom_field_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field', to='recaps.customrecapfieldtype')),
                ('custom_recap_template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field', to='recaps.customrecaptemplate')),
                ('recap_section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field', to='recaps.recapsection')),
            ],
        ),
    ]
