# Generated by Django 5.2.7 on 2026-04-09 19:40

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0017_ambassador_about_me'),
        ('recaps', '0019_customrecap_customrecapfieldtype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_value_created_by', to=settings.AUTH_USER_MODEL)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_value', to='recaps.customfield')),
                ('custom_recap', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_value', to='recaps.customrecap')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_field_value_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomRecapFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('name', models.TextField(null=True)),
                ('url', models.FileField(max_length=1024, null=True, upload_to='recap_files/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_files_created_by', to=settings.AUTH_USER_MODEL)),
                ('custom_recap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_files', to='recaps.customrecap')),
                ('file_recap_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_files', to='recaps.filerecapcategory')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_files', to='ambassadors.filetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='custom_recap_files_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
