# Generated by Django 5.2.7 on 2026-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0021_recap_external_ba_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrecap',
            name='external_ba_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
