# Generated by Django 5.2.7 on 2026-05-31 21:14

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # Build these indexes with CREATE INDEX CONCURRENTLY so the deploy does
    # NOT take an ACCESS EXCLUSIVE lock / block writes on recaps_recap or
    # recaps_customrecap while the index builds on the production tables.
    # CONCURRENTLY cannot run inside a transaction, so the whole migration
    # must be non-atomic.
    atomic = False

    dependencies = [
        ('ambassadors', '0023_ambassador_bio_ambassador_college_and_more'),
        ('events', '0047_event_ev_event_tenant_date_idx_and_more'),
        ('jobs', '0022_ambassadorjobpreference'),
        ('recaps', '0022_customrecap_external_ba_name'),
        ('tenants', '0016_tenant_default_external_rmm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='customrecap',
            index=models.Index(fields=['tenant', '-created_at'], name='rc_customrecap_t_created_idx'),
        ),
        AddIndexConcurrently(
            model_name='recap',
            index=models.Index(fields=['-created_at'], name='rc_recap_created_idx'),
        ),
    ]
