# Generated by Django 5.2.7 on 2026-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0023_customrecap_rc_customrecap_t_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecapQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recap_id', models.BigIntegerField()),
                ('is_custom', models.BooleanField(default=False)),
                ('low_quality', models.BooleanField(default=False)),
                ('label', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recap_id', 'is_custom'), name='rc_recap_quality_snapshot_uniq')],
            },
        ),
    ]
