# Generated by Django 5.2.7 on 2026-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0024_recapqualitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recapsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
