# Generated by Django 5.2.7 on 2026-06-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0025_customfield_order_recapsection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
