# Generated by Django 5.2.7 on 2026-10-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0036_recap_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrecap',
            name='exclude_from_aggregates',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
