# Generated by Django 5.2.7 on 2026-10-08 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_field_marketing_taxonomy'),
        ('recaps', '0037_exclude_from_aggregates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanRecapLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_keys', models.JSONField(blank=True, default=list)),
                ('auto', models.BooleanField(default=False)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_recap_links', to=settings.AUTH_USER_MODEL)),
                ('custom_recap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_link', to='recaps.customrecap')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recap_links', to='events.fieldmarketingevent')),
                ('recap', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_link', to='recaps.recap')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('custom_recap__isnull', True), ('recap__isnull', False)), models.Q(('custom_recap__isnull', False), ('recap__isnull', True)), _connector='OR'), name='rc_plan_link_one_recap')],
            },
        ),
    ]
