# Generated by Django 5.2.7 on 2026-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recaps', '0039_recap_metric_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrecap',
            name='source_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
