# Generated by Django 5.2.7 on 2026-05-19 20:16

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0014_tenant_linked_sheet_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('training', 'Training'), ('brand', 'Brand'), ('playbook', 'Playbook'), ('policy', 'Policy'), ('announcement', 'Announcement')], default='training', max_length=24)),
                ('body', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='academy_modules_created_by', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='academy_modules', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='academy_modules_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'published', 'order'], name='academy_aca_tenant__98c662_idx')],
            },
        ),
    ]
