# Generated by Django 5.2.7 on 2026-08-02 23:43

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('tenants', '0034_checkin_markets_and_sampling_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingHub',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid6.uuid7, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('intro', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='training_hubs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant_id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('link', 'Link'), ('page', 'Page')], default='link', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, default='', max_length=500)),
                ('meta_label', models.CharField(blank=True, default='', max_length=60)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academy.traininghub')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['hub', 'published', 'order'], name='academy_tra_hub_id_6cb076_idx')],
            },
        ),
    ]
