# Generated by Django 5.2.7 on 2026-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackendErrorEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('signature', models.CharField(db_index=True, max_length=255, unique=True)),
                ('message', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('traceback', models.TextField(blank=True, default='')),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
